# Generated by Django 2.1.4 on 2019-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.TextField(default='')),
                ('timesViewed', models.IntegerField(default=0)),
                ('lastJump', models.IntegerField(default=0)),
                ('lastViewed', models.DateField(auto_now_add=True)),
                ('right_answer', models.TextField(default='')),
                ('wrong_answer1', models.TextField(default='')),
                ('wrong_answer2', models.TextField(default='')),
                ('wrong_answer3', models.TextField(default='')),
            ],
        ),
    ]
