# Generated by Django 2.1.4 on 2018-12-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to=None,
        ),
    ]
